/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author azri
 */
public class Anggotaa extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form Anggotaa
     */
    public Anggotaa() {
        initComponents();
        datatable();
        combo_pangkat();
        combo_kesatuan();
        lpangkat.hide();
        lkesatuan.hide();  
    }
    
    public void datatable(){
       Object[] Baris ={"NRP","Nama","Pangkat","Kesatuan"};
        tabmode = new DefaultTableModel(null,Baris);
        tabel_anggota.setModel(tabmode);
       
        String sql = "select anggota.nrp,anggota.nama,kesatuan.kesatuan,pangkat.pangkat from anggota,kesatuan,pangkat where pangkat.id_pangkat=anggota.id_pangkat and kesatuan.id_kesatuan=anggota.id_kesatuan";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);            
            while(hasil.next()){               
                String a = hasil.getString("anggota.nrp");
                String b = hasil.getString("anggota.nama");
                String c = hasil.getString("pangkat.pangkat");
                String d = hasil.getString("kesatuan.kesatuan");
                
                String[] data={a,b,c,d};
                tabmode.addRow(data);
            }
        }catch (Exception e){
            
        }
    }
    
    
    
    
    public void combo_pangkat(){
             
        String sql = "select pangkat from pangkat order by id_pangkat asc";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){               
            Object[] ob = new Object[3];
            ob[0] = hasil.getString(1);
            
            cpangkat.addItem((String) ob[0]);   
            }
        }catch (Exception e){
            
        }
    }
    
    
    
    public void combo_kesatuan(){
        String sql = "select kesatuan from kesatuan order by id_kesatuan asc";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){               
            Object[] ob = new Object[3];
            ob[0] = hasil.getString(1);
            
            ckesatuan.addItem((String) ob[0]);   
            }
        }catch (Exception e){
            
        }
    }
    
    public void bersih(){
        tnrp.setText(null);
        tnama.setText(null);
        ckesatuan.setSelectedIndex(0);
        cpangkat.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnrp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_konfirmasi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cpangkat = new javax.swing.JComboBox<>();
        ckesatuan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lpangkat = new javax.swing.JLabel();
        lkesatuan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_anggota = new javax.swing.JTable();
        tcari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YASBHUM [Anggota]");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/tampilan/icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fom Angota");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NRP");

        tnrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnrpActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");

        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pangkat");

        btn_konfirmasi.setBackground(new java.awt.Color(255, 102, 102));
        btn_konfirmasi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_konfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        btn_konfirmasi.setText("Masukan Data");
        btn_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfirmasiActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kesatuan");

        cpangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Pangkat --" }));
        cpangkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpangkatMouseClicked(evt);
            }
        });
        cpangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpangkatActionPerformed(evt);
            }
        });

        ckesatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kesatuan --" }));
        ckesatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckesatuanActionPerformed(evt);
            }
        });

        lpangkat.setText("pangkat");

        lkesatuan.setText("kesatuan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(tnama)
                        .addComponent(btn_konfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(tnrp)
                        .addComponent(cpangkat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckesatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lpangkat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lkesatuan)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tnrp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckesatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpangkat)
                    .addComponent(lkesatuan))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );

        tabel_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_anggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_anggota);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 153, 153));
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit Data");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_cetak.setText("Cetak Laporan");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        bkembali.setText("Kembali");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_edit)
                            .addGap(18, 18, 18)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cetak))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bkembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(bkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnrpActionPerformed

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void btn_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfirmasiActionPerformed
        // TODO add your handling code here:
        if(tnrp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NRP Tidak Boleh Kosong","Peringatan",0);
        }else if(tnama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama Anggota Tidak Boleh Kosong","Peringatan",0);
        }else if(cpangkat.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Harap pilih Pangkat terlebih dahulu","Peringatan",0);
        }else if(ckesatuan.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Harap pilih Kesatuan terlebih dahulu","Peringatan",0);
        }else{
            String sql="insert into anggota values(?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, tnrp.getText());
                stat.setString(2, tnama.getText());
                stat.setString(3, lpangkat.getText());
                stat.setString(4, lkesatuan.getText());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                datatable();

                bersih();

            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan : ID Pangkat sudah ada \n"+e);

            }
        }
    }//GEN-LAST:event_btn_konfirmasiActionPerformed

    private void cpangkatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpangkatMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cpangkatMouseClicked

    private void cpangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpangkatActionPerformed
        // TODO add your handling code here:
        String sql = "select id_pangkat from pangkat where pangkat='"+cpangkat.getSelectedItem().toString()+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String pangkat = hasil.getString("id_pangkat");
                lpangkat.setText(pangkat);
            }
        }catch (Exception e){

        }
    }//GEN-LAST:event_cpangkatActionPerformed

    private void ckesatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckesatuanActionPerformed
        // TODO add your handling code here:
        String sql = "select id_kesatuan from kesatuan where kesatuan='"+ckesatuan.getSelectedItem().toString()+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String pangkat = hasil.getString("id_kesatuan");
                lkesatuan.setText(pangkat);
            }
        }catch (Exception e){

        }
    }//GEN-LAST:event_ckesatuanActionPerformed

    private void tabel_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_anggotaMouseClicked
        // TODO add your handling code here:
        int bar = tabel_anggota.getSelectedRow();
        String a =tabmode.getValueAt(bar, 0).toString();
        String b =tabmode.getValueAt(bar, 1).toString();
        String c =tabmode.getValueAt(bar, 2).toString();
        String d =tabmode.getValueAt(bar, 3).toString();

        tnrp.setText(a);
        tnama.setText(b);
        cpangkat.setSelectedItem(c);
        ckesatuan.setSelectedItem(d);

    }//GEN-LAST:event_tabel_anggotaMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        if(tcari.getText().equals("")){
            datatable();
        }else{
            Object[] Baris ={"NRP","Nama","Pangkat","Kesatuan"};
            tabmode = new DefaultTableModel(null,Baris);
            tabel_anggota.setModel(tabmode);

            String sql = "select anggota.nrp,anggota.nama,kesatuan.kesatuan,pangkat.pangkat from anggota,kesatuan,pangkat where pangkat.id_pangkat=anggota.id_pangkat and kesatuan.id_kesatuan=anggota.id_kesatuan and anggota.nama='"+tcari.getText()+"'";
            try{
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while(hasil.next()){
                    String a = hasil.getString("anggota.nrp");
                    String b = hasil.getString("anggota.nama");
                    String c = hasil.getString("pangkat.pangkat");
                    String d = hasil.getString("kesatuan.kesatuan");

                    String[] data={a,b,c,d};
                    tabmode.addRow(data);
                }
            }catch (Exception e){

            }
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        if(tnrp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NRP Tidak Boleh Kosong","Peringatan",0);
        }else if(tnama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama Anggota Tidak Boleh Kosong","Peringatan",0);
        }else if(cpangkat.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Harap pilih Pangkat terlebih dahulu","Peringatan",0);
        }else if(ckesatuan.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Harap pilih Kesatuan terlebih dahulu","Peringatan",0);
        }else{
            try{
                String sql = "update anggota set nama=?,id_pangkat=?,id_kesatuan=? where nrp=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1,tnama.getText());
                stat.setString(2,lpangkat.getText());
                stat.setString(3,lkesatuan.getText());
                stat.setString(4,tnrp.getText());
                stat.executeUpdate();
                datatable();

                bersih();
                JOptionPane.showMessageDialog(null,"Berhasil Diubah");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal Diubah : "+e);
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if(tnrp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Harap Pilih Data Terlebih Dahulu","Peringatan",0);
        }else{
            int ok = JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
            if(ok==0){
                String sql = "delete from kesatuan where id_kesatuan='"+tnrp.getText()+"'";
                try{
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                    datatable();

                    bersih();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Data Gagal Dihapus : "+e);
                }
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        // TODO add your handling code here:
        Santunann re=new Santunann();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bkembaliActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Masukkan Kesatuan atau Kosongkan untuk tampil semua data : ");
        JOptionPane.showMessageDialog(this, "Menampilkan :"+input);
        if(input.equals("")){
            try{            
            String namaFile = "src/tampilan/Keanggotaan_1.jasper";
            HashMap parameter = new HashMap(1);
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }else{
        try{            
            String namaFile = "src/tampilan/Keanggotaan.jasper";
            HashMap parameter = new HashMap(1);
            parameter.put("kesatuan",input);
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggotaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggotaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggotaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggotaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anggotaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkembali;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_konfirmasi;
    private javax.swing.JComboBox<String> ckesatuan;
    private javax.swing.JComboBox<String> cpangkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lkesatuan;
    private javax.swing.JLabel lpangkat;
    private javax.swing.JTable tabel_anggota;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnrp;
    // End of variables declaration//GEN-END:variables
}
