/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author azri
 */
public class Santunann extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public Properties prop = new Properties();
    /**
     * Creates new form NewJFrame
     */
    public Santunann() {
        initComponents();
        combo_pangkat();
        datatable();
        lpangkat.hide();
        lidpangkat.hide();
    }
    public void datatable(){
       Object[] Baris ={"Id Santunan","NRP","Nama","Pangkat","Kesatuan","Tanggal Meninggal","Jumlah Santunan"};
        tabmode = new DefaultTableModel(null,Baris);
        tabel_santunan.setModel(tabmode);
        try{
            String sql = "select santunan.id_santunan,anggota.nrp,anggota.nama,pangkat.pangkat,kesatuan.kesatuan,santunan.tanggal_meninggal,pangkat.jumlah_santunan from santunan,anggota,pangkat,kesatuan where anggota.nrp = santunan.nrp and pangkat.id_pangkat = anggota.id_pangkat and kesatuan.id_kesatuan = anggota.id_kesatuan";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            String anumerta = "ANUMERTA ";
            while(hasil.next()){               
                String a = hasil.getString("santunan.id_santunan");
                String b = hasil.getString("anggota.nrp");
                String c = hasil.getString("anggota.nama");
                String d = hasil.getString("pangkat.pangkat");
                String e = hasil.getString("kesatuan.kesatuan");
                String f = hasil.getString("santunan.tanggal_meninggal");
                String g = hasil.getString("pangkat.jumlah_santunan");
                String[] data={a,b,c,anumerta+d,e,f,g};
                tabmode.addRow(data);
            }
        }catch (Exception e){
            
        }
    }
    
    public void idpangkat(){
        String sql = "select id_pangkat from pangkat where pangkat='"+lpangkat.getText()+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){               
            String a = hasil.getString("id_pangkat");
            lidpangkat.setText(a);
            }
        }catch (Exception e){
            
        }
    }
    
    public void combo_pangkat(){
             
        String sql = "select pangkat from pangkat order by id_pangkat asc";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            String anumerta = "ANUMERTA ";
            while(hasil.next()){               
            Object[] ob = new Object[3];
            ob[0] = hasil.getString(1);
            
            cpangkat.addItem((String) anumerta+ob[0]);   
            }
        }catch (Exception e){
            
        }
    }
    
    public void bersih(){
        tid.setText(null);
        tnama.setText(null);
        cpangkat.setSelectedIndex(0);
        tkesatuan.setText(null);
        ctgl.setDate(null);
        tsantunan.setText(null);
    }
    
    public void bersih2(){
        
        tnama.setText(null);
        cpangkat.setSelectedIndex(0);
        tkesatuan.setText(null);
        ctgl.setDate(null);
        tsantunan.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnrp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tsantunan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ctgl = new com.toedter.calendar.JDateChooser();
        tid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tkesatuan = new javax.swing.JTextField();
        cpangkat = new javax.swing.JComboBox<>();
        lpangkat = new javax.swing.JLabel();
        lidpangkat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_santunan = new javax.swing.JTable();
        btn_cari = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YASBHUM [Santunan Duka]");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/tampilan/icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fom Santunan Duka");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NRP");

        tnrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnrpActionPerformed(evt);
            }
        });
        tnrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnrpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnrpKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");

        tnama.setEnabled(false);
        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Masukan Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pangkat");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kesatuan");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Meninggal");

        tsantunan.setText("Rp.");
        tsantunan.setEnabled(false);
        tsantunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsantunanActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jumlah Santunan");

        ctgl.setDateFormatString("dd/M/yyyy");

        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Santunan");

        tkesatuan.setEnabled(false);
        tkesatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkesatuanActionPerformed(evt);
            }
        });

        cpangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Pangkat--" }));
        cpangkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpangkatMouseClicked(evt);
            }
        });
        cpangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpangkatActionPerformed(evt);
            }
        });
        cpangkat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpangkatKeyPressed(evt);
            }
        });

        lpangkat.setText("jLabel2");

        lidpangkat.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tkesatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lpangkat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lidpangkat))
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ctgl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tsantunan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cpangkat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tnrp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tnama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tnrp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lpangkat)
                    .addComponent(lidpangkat))
                .addGap(15, 15, 15)
                .addComponent(cpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(tkesatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tsantunan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabel_santunan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_santunan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_santunanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_santunan);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Edit Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak Laporan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Insert");

        jMenuItem1.setText("Anggota");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Kesatuan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Pangkat");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Restore");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Backup");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnrpActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tnrpActionPerformed

    private void tnrpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnrpKeyReleased
        // TODO add your handling code here:
        if(tnrp.getText().equals("")){
            bersih2();
        }else{
            try{
                String sql = "select anggota.nama,pangkat.pangkat,kesatuan.kesatuan,pangkat.jumlah_santunan from anggota,pangkat,kesatuan where pangkat.id_pangkat = anggota.id_pangkat and kesatuan.id_kesatuan = anggota.id_kesatuan and anggota.nrp = '"+tnrp.getText()+"'";
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                String anumerta = "ANUMERTA ";
                while(hasil.next()){
                    String a = hasil.getString("anggota.nama");
                    String b = hasil.getString("pangkat.pangkat");
                    String c = hasil.getString("kesatuan.kesatuan");
                    String d = hasil.getString("pangkat.jumlah_santunan");
                    tnama.setText(a);
                    cpangkat.setSelectedItem(anumerta+b);
                    tkesatuan.setText(c);
                    tsantunan.setText(d);
                }
            }catch (Exception e){

            }
        }
    }//GEN-LAST:event_tnrpKeyReleased

    private void tnrpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnrpKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_tnrpKeyTyped

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ID Santunan Tidak Boleh Kosong","Peringatan",0);
        }else if(tnrp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NRP Tidak Boleh Kosong","Peringatan",0);
        }else if(ctgl.getDate().toString().equals("")){
            JOptionPane.showMessageDialog(null,"Tanggal Meninggal Tidak Boleh Kosong","Peringatan",0);
        }else{
            try{
                String sql="insert into santunan values(?,?,?)";
                String tampilan ="yyyy-MM-dd" ;
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                String tgl = String.valueOf(fm.format(ctgl.getDate()));
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, tid.getText());
                stat.setString(2, tnrp.getText());
                stat.setString(3, tgl);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan : ID Pangkat sudah ada \n"+e);

            }
            try{
                String sql = "update anggota set id_pangkat=? where nrp=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1,lidpangkat.getText());
                stat.setString(2,tnrp.getText());
                stat.executeUpdate();
                datatable();
                bersih();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal Diubah : "+e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tsantunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsantunanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsantunanActionPerformed

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void tkesatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkesatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkesatuanActionPerformed

    private void cpangkatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpangkatMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cpangkatMouseClicked

    private void cpangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpangkatActionPerformed
        // TODO add your handling code here:
        int panjang = cpangkat.getSelectedItem().toString().length();
        String pangkat = cpangkat.getSelectedItem().toString().substring(9,panjang);
        lpangkat.setText(pangkat);
        idpangkat();
    }//GEN-LAST:event_cpangkatActionPerformed

    private void cpangkatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpangkatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpangkatKeyPressed

    private void tabel_santunanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_santunanMouseClicked
        // TODO add your handling code here:
        int bar = tabel_santunan.getSelectedRow();
        String a =tabmode.getValueAt(bar, 0).toString();
        String b =tabmode.getValueAt(bar, 1).toString();
        String c =tabmode.getValueAt(bar, 2).toString();
        String d =tabmode.getValueAt(bar, 3).toString();
        String e =tabmode.getValueAt(bar, 4).toString();
        String f=(String)tabel_santunan.getModel().getValueAt(bar, 5);
        String g =tabmode.getValueAt(bar, 6).toString();
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date tgl;
            tgl = sd.parse(f);
            ctgl.setDate(tgl);
        } catch (ParseException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        tid.setText(a);
        tnrp.setText(b);
        tnama.setText(c);

        cpangkat.setSelectedItem(d);
        tkesatuan.setText(e);
        tsantunan.setText(g);
        idpangkat();

    }//GEN-LAST:event_tabel_santunanMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        if(tcari.getText().equals("")){
            datatable();
        }else{
            Object[] Baris ={"Id Santunan","NRP","Nama","Pangkat","Kesatuan","Tanggal Meninggal","Jumlah Santunan"};
            tabmode = new DefaultTableModel(null,Baris);
            tabel_santunan.setModel(tabmode);
            try{
                String sql = "select santunan.id_santunan,anggota.nrp,anggota.nama,pangkat.pangkat,kesatuan.kesatuan,santunan.tanggal_meninggal,pangkat.jumlah_santunan from santunan,anggota,pangkat,kesatuan where anggota.nrp = santunan.nrp and pangkat.id_pangkat = anggota.id_pangkat and kesatuan.id_kesatuan = anggota.id_kesatuan and santunan.id_santunan = '"+tcari.getText()+"'";
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                String anumerta = "ANUMERTA ";
                while(hasil.next()){
                    String a = hasil.getString("santunan.id_santunan");
                    String b = hasil.getString("anggota.nrp");
                    String c = hasil.getString("anggota.nama");
                    String d = hasil.getString("pangkat.pangkat");
                    String e = hasil.getString("kesatuan.kesatuan");
                    String f = hasil.getString("santunan.tanggal_meninggal");
                    String g = hasil.getString("pangkat.jumlah_santunan");
                    String[] data={a,b,c,anumerta+d,e,f,g};
                    tabmode.addRow(data);
                }
            }catch (Exception e){

            }
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            String tampilan ="yyyy-MM-dd" ;
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tgl = String.valueOf(fm.format(ctgl.getDate()));
            String sql = "update santunan set nrp=?,tanggal_meninggal=? where id_santunan='"+tid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,tnrp.getText());
            stat.setString(2,tgl);
            stat.setString(3,tid.getText());
            stat.executeUpdate();
            datatable();
            bersih();
            JOptionPane.showMessageDialog(null,"Berhasil Diubah");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal Diubah : "+e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tnrp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Harap Pilih Data Terlebih Dahulu","Peringatan",0);
        }else{
            int ok = JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
            if(ok==0){
                String sql = "delete from santunan where id_santunan='"+tid.getText()+"'";
                try{
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                    datatable();

                    bersih();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Data Gagal Dihapus : "+e);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            String namaFile = "src/tampilan/Santunan.jasper";
            HashMap parameter = new HashMap(1);
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Anggotaa re=new Anggotaa();
                        re.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Kesatuann re=new Kesatuann();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Pangkatt re=new Pangkatt();
        re.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        InputStream input = null;
        JFileChooser fc = new JFileChooser("C:/");
        fc.setFileFilter(new FileNameExtensionFilter("SQL File", "sql"));
        fc.showOpenDialog(this);
        String path=null;
                   
        
        try {
            
            File f = fc.getSelectedFile();
            path = f.getAbsolutePath();
            path = path.replace('\\', '/');

            if(path==null){
                
            }else{
            input = new FileInputStream("config.txt");
            prop.load(input);
            String user = prop.getProperty("user");
            String pass = prop.getProperty("pass");
            String pathh = prop.getProperty("path")+"mysql.exe ";
            String[] restoreCmd = new String[]{pathh, "--user=" + user, "--password=" + pass, "-e", "source " + path};
            Process runtimProcess;
            runtimProcess = Runtime.getRuntime().exec(restoreCmd);
            int proceCom = runtimProcess.waitFor();
            if (proceCom==0) {
                JOptionPane.showMessageDialog(null,"Berhasil Di Restore");
                MainMenu mn=new MainMenu();
                mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mn.setVisible(true);
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null,"Gagal Di Restore");
            }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        InputStream input = null;
        int ok = JOptionPane.showConfirmDialog(null,"Data Akan di Backup?","Backup",JOptionPane.YES_NO_OPTION);
        if(ok==0){
        try {
            String date = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
            //File file = new File("C:/Sanduk/");
            //input = new FileInputStream(file.getAbsolutePath()+"/config.txt");
            input = new FileInputStream("config.txt");
            prop.load(input);
            String folderpath = "src" + "\\Backup database";
                
                File fl = new File(folderpath);
                fl.mkdir();
                
                String savepath = "\"" + folderpath + "\\" + "" + "Sanduk_"+ date + ""+".sql\"";
            
            String user=prop.getProperty("user");
            String pass=prop.getProperty("pass");
            String path=prop.getProperty("path")+"mysqldump -u"+user+" --password="+pass+" --add-drop-database -B sanduk -r "+savepath;
            Runtime rn=Runtime.getRuntime();
            Process pr=rn.exec(path);
            int hitung = pr.waitFor();
            if(hitung==0)
            JOptionPane.showMessageDialog(null,"Berhasil Di Backup");
            else JOptionPane.showMessageDialog(null,"Gagal Di Backup");
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Santunann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Santunann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Santunann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Santunann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Santunann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JComboBox<String> cpangkat;
    private com.toedter.calendar.JDateChooser ctgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lidpangkat;
    private javax.swing.JLabel lpangkat;
    private javax.swing.JTable tabel_santunan;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tkesatuan;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnrp;
    private javax.swing.JTextField tsantunan;
    // End of variables declaration//GEN-END:variables
}
